name: Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-crate:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal toolchain with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Run tests
        # test threads must be one because else database tests will run in parallel and will result in flaky tests
        run: cargo test --all-features --verbose
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy check
        run: cargo clippy --all-targets --all-features -- -D warnings
